@startuml
class inventorymanagementsystem.ProductManagement.View.EditProductFrame {
~ DBConnection dbc
~ String userId
- javax.swing.JButton btnAdd
- javax.swing.JLabel jLabel1
- javax.swing.JLabel jLabel2
- javax.swing.JLabel jLabel3
- javax.swing.JLabel jLabel4
- javax.swing.JLabel jLabel5
- javax.swing.JLabel jLabel6
- javax.swing.JLabel jLabel7
- javax.swing.JLabel jLabel8
- javax.swing.JLabel jLabel9
- javax.swing.JPanel jPanel1
- javax.swing.JPanel jPanel2
- javax.swing.JComboBox<String> jcbType
- javax.swing.JLabel lblProc
- javax.swing.JTextField txtBrand
- javax.swing.JTextField txtModel
- javax.swing.JTextField txtPrice
- javax.swing.JTextField txtProc
- javax.swing.JTextField txtProdID
- javax.swing.JTextField txtQuantity
- javax.swing.JTextField txtRAM
- javax.swing.JTextField txtStorage
+ void loadData(String)
- void initComponents()
- void jcbTypeItemStateChanged(java.awt.event.ItemEvent)
- void btnAddActionPerformed(java.awt.event.ActionEvent)
+ void showHideproc()
+ {static} void main(String[])
}
class inventorymanagementsystem.ProductManagement.View.AddProductFrame {
- javax.swing.JButton btnAdd
- javax.swing.JLabel jLabel1
- javax.swing.JLabel jLabel2
- javax.swing.JLabel jLabel3
- javax.swing.JLabel jLabel4
- javax.swing.JLabel jLabel5
- javax.swing.JLabel jLabel6
- javax.swing.JLabel jLabel7
- javax.swing.JLabel jLabel8
- javax.swing.JPanel jPanel1
- javax.swing.JPanel jPanel2
- javax.swing.JComboBox<String> jcbType
- javax.swing.JLabel lblProc
- javax.swing.JTextField txtBrand
- javax.swing.JTextField txtModel
- javax.swing.JTextField txtPrice
- javax.swing.JTextField txtProc
- javax.swing.JTextField txtQuantity
- javax.swing.JTextField txtRAM
- javax.swing.JTextField txtStorage
+ void showHideproc()
- void initComponents()
- void btnAddActionPerformed(java.awt.event.ActionEvent)
- void jcbTypeItemStateChanged(java.awt.event.ItemEvent)
- void formWindowGainedFocus(java.awt.event.WindowEvent)
+ {static} void main(String[])
}
class inventorymanagementsystem.ProductManagement.Model.ComputerBuilder {
- String type
- String processor
- int ram
- int storage
- String brand
- String model
- int quantity
- double price
- {static} ComputerBuilder instance
+ {static} ComputerBuilder getInstance()
+ ComputerBuilder setType(String)
+ ComputerBuilder setProcessor(String)
+ ComputerBuilder setRam(int)
+ ComputerBuilder setStorage(int)
+ ComputerBuilder setBrand(String)
+ ComputerBuilder setModel(String)
+ ComputerBuilder setQuantity(int)
+ ComputerBuilder setPrice(double)
+ Computer build()
}
class inventorymanagementsystem.ProductManagement.Model.Electronic {
+ String brand
+ String model
+ int quantity
+ double price
+ String getBrand()
+ void setBrand(String)
+ String getModel()
+ void setModel(String)
+ int getQuantity()
+ void setQuantity(int)
+ double getPrice()
+ void setPrice(double)
}
class inventorymanagementsystem.ProductManagement.Model.PhoneBuilder {
- String type
- String os
- int ram
- int storage
- String brand
- String model
- int quantity
- double price
- {static} PhoneBuilder instance
+ {static} PhoneBuilder getInstance()
+ PhoneBuilder setType(String)
+ PhoneBuilder setOs(String)
+ PhoneBuilder setRam(int)
+ PhoneBuilder setStorage(int)
+ PhoneBuilder setBrand(String)
+ PhoneBuilder setModel(String)
+ PhoneBuilder setQuantity(int)
+ PhoneBuilder setPrice(double)
+ Phone build()
}
class inventorymanagementsystem.ProductManagement.View.DeleteProductFrame {
~ String userId
- javax.swing.JButton btnCancel
- javax.swing.JButton btnYes
- javax.swing.JLabel jLabel1
- javax.swing.JLabel jLabel10
- javax.swing.JLabel jLabel2
- javax.swing.JLabel jLabel3
- javax.swing.JLabel jLabel4
- javax.swing.JLabel jLabel5
- javax.swing.JLabel jLabel6
- javax.swing.JLabel jLabel7
- javax.swing.JLabel jLabel9
- javax.swing.JPanel jPanel2
- javax.swing.JLabel jlabel
- javax.swing.JLabel jlabelef
- javax.swing.JLabel lblBrand
- javax.swing.JLabel lblModel
- javax.swing.JLabel lblPrice
- javax.swing.JLabel lblProc
- javax.swing.JLabel lblProdID
- javax.swing.JLabel lblProdType
- javax.swing.JLabel lblQuantity
- javax.swing.JLabel lblRam
- javax.swing.JLabel lblStorage
- void initComponents()
- void btnCancelActionPerformed(java.awt.event.ActionEvent)
- void btnYesActionPerformed(java.awt.event.ActionEvent)
+ void loadData(String)
+ {static} void main(String[])
}
class inventorymanagementsystem.ProductManagement.Controller.ProductController {
+ void AddProduct(String,String,String,int,int,double,int,String)
+ void EditProduct(Computer,String)
+ void EditProduct(Phone,String)
+ void DeleteProduct(String)
}
class inventorymanagementsystem.ProductManagement.Model.TestClass {
+ {static} void main(String[])
}
class inventorymanagementsystem.ProductManagement.View.MainMenuFrame {
~ User user
- javax.swing.JButton btnAddProd
- javax.swing.JButton btnDeleteProd
- javax.swing.JButton btnEditProd
- javax.swing.JLabel jLabel5
- javax.swing.JPanel jPanel2
- javax.swing.JScrollPane jScrollPane1
- javax.swing.JTable jTable1
- javax.swing.JLabel lblLoginas
- javax.swing.JLabel lblWelcome
- void loadData()
+ void reloadTable()
- void initComponents()
- void btnAddProdActionPerformed(java.awt.event.ActionEvent)
- void formWindowGainedFocus(java.awt.event.WindowEvent)
- void btnEditProdActionPerformed(java.awt.event.ActionEvent)
- void btnDeleteProdActionPerformed(java.awt.event.ActionEvent)
+ {static} void main(String[])
}
class inventorymanagementsystem.ProductManagement.Model.Computer {
+ String type
+ String processor
+ int ram
+ int storage
}
class inventorymanagementsystem.ProductManagement.Model.Phone {
+ String type
+ String os
+ int ram
+ int storage
}


inventorymanagementsystem.ProductManagement.View.JFrame <|-- inventorymanagementsystem.ProductManagement.View.EditProductFrame
inventorymanagementsystem.ProductManagement.View.JFrame <|-- inventorymanagementsystem.ProductManagement.View.AddProductFrame
inventorymanagementsystem.ProductManagement.View.JFrame <|-- inventorymanagementsystem.ProductManagement.View.DeleteProductFrame
inventorymanagementsystem.ProductManagement.View.JFrame <|-- inventorymanagementsystem.ProductManagement.View.MainMenuFrame
inventorymanagementsystem.ProductManagement.Model.Electronic <|-- inventorymanagementsystem.ProductManagement.Model.Computer
inventorymanagementsystem.ProductManagement.Model.Electronic <|-- inventorymanagementsystem.ProductManagement.Model.Phone
@enduml